version: "2"

services:
  web:
    restart: always
    image: ghcr.io/arnested/aula-assistant:latest
    volumes:
      - './calendar.ics:/calendar.ics:ro'
    labels:
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:aula-assistant.arnested.dk"
    networks:
      - web

networks:
  web:
    external:
      name: traefik_webgateway
